project:
  type: website
  output-dir: docs
  resources:
    - dashboard/theme/  # Copies theme/ folder to docs/dashboard/

website:
  title: "sofiyavyshnya"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: blog/index.qmd
        text: Blog
      - text: Dashboard
        menu:
        - href: dashboard/dashboard.qmd
          text: Dashboard
        - href: blog/posts/2025-09-27-ProjectA-TaskB/study1_analyses/nhanes_data_exploration.qmd
          text: Data Exploration (Study 1)
        - href: blog/posts/2025-09-27-ProjectA-TaskB/study2_analyses/nhanes_bp_leadExposure.qmd
          text: BP Determinants (Study 2)
      - href: contact.qmd
        text: Contact

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    include-in-header:
      - text: |
          <!-- Load Academicons for CV, Google Scholar, ORCID -->
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons/css/academicons.min.css"/>
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"/>


