<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.24">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Sofiya Vyshnya">
<meta name="dcterms.date" content="2025-09-27">

<title>NHANES Data Exploration (Heavy Metal Exposure &amp; High blood Pressure) – sofiyavyshnya</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../../">
<script src="../../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../../site_libs/quarto-html/quarto-syntax-highlighting-dc55a5b9e770e841cd82e46aadbfb9b0.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../../site_libs/bootstrap/bootstrap-e31584831b205ffbb2d98406f31c2a5b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="../../../../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../../../../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../../../../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<!-- Load Academicons for CV, Google Scholar, ORCID -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons/css/academicons.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../../../styles.css">
</head>

<body class="floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../../../index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="../../../../index.html">
    <span class="navbar-title">sofiyavyshnya</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../../research.html"> 
<span class="menu-text">Research</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../../blog/index.html"> 
<span class="menu-text">Blog</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../../contact.html"> 
<span class="menu-text">Contact</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#central-hypothesis" id="toc-central-hypothesis" class="nav-link active" data-scroll-target="#central-hypothesis"><span class="header-section-number">1</span> Central Hypothesis</a></li>
  <li><a href="#import-helper-functions" id="toc-import-helper-functions" class="nav-link" data-scroll-target="#import-helper-functions"><span class="header-section-number">2</span> Import Helper Functions</a></li>
  <li><a href="#setup-and-data-ingest" id="toc-setup-and-data-ingest" class="nav-link" data-scroll-target="#setup-and-data-ingest"><span class="header-section-number">3</span> Setup and Data Ingest</a></li>
  <li><a href="#data-cleaning" id="toc-data-cleaning" class="nav-link" data-scroll-target="#data-cleaning"><span class="header-section-number">4</span> Data Cleaning</a></li>
  <li><a href="#dataset-description-and-codebook" id="toc-dataset-description-and-codebook" class="nav-link" data-scroll-target="#dataset-description-and-codebook"><span class="header-section-number">5</span> Dataset Description and Codebook</a>
  <ul class="collapse">
  <li><a href="#dataset-description-summary-statistics" id="toc-dataset-description-summary-statistics" class="nav-link" data-scroll-target="#dataset-description-summary-statistics"><span class="header-section-number">5.1</span> Dataset Description &amp; Summary Statistics</a></li>
  <li><a href="#codebook-html-rendering" id="toc-codebook-html-rendering" class="nav-link" data-scroll-target="#codebook-html-rendering"><span class="header-section-number">5.2</span> Codebook (HTML Rendering)</a></li>
  <li><a href="#codebook-table-rendering" id="toc-codebook-table-rendering" class="nav-link" data-scroll-target="#codebook-table-rendering"><span class="header-section-number">5.3</span> Codebook (Table Rendering)</a></li>
  <li><a href="#analytic-tibble" id="toc-analytic-tibble" class="nav-link" data-scroll-target="#analytic-tibble"><span class="header-section-number">5.4</span> Analytic Tibble</a></li>
  </ul></li>
  <li><a href="#summary-statistics" id="toc-summary-statistics" class="nav-link" data-scroll-target="#summary-statistics"><span class="header-section-number">6</span> Summary Statistics</a></li>
  <li><a href="#study-1-analyses" id="toc-study-1-analyses" class="nav-link" data-scroll-target="#study-1-analyses"><span class="header-section-number">7</span> Study 1 Analyses</a>
  <ul class="collapse">
  <li><a href="#analysis-b-comparing-2-means-with-independent-samples-blood-lead-levels-by-sex" id="toc-analysis-b-comparing-2-means-with-independent-samples-blood-lead-levels-by-sex" class="nav-link" data-scroll-target="#analysis-b-comparing-2-means-with-independent-samples-blood-lead-levels-by-sex"><span class="header-section-number">7.1</span> Analysis B: Comparing 2 Means with Independent Samples (Blood Lead Levels by Sex)</a></li>
  <li><a href="#analysis-c-comparing-blood-lead-levels-across-races" id="toc-analysis-c-comparing-blood-lead-levels-across-races" class="nav-link" data-scroll-target="#analysis-c-comparing-blood-lead-levels-across-races"><span class="header-section-number">7.2</span> Analysis C: Comparing Blood Lead Levels Across Races</a></li>
  </ul></li>
  <li><a href="#analysis-d-analyzing-a-2x2-table" id="toc-analysis-d-analyzing-a-2x2-table" class="nav-link" data-scroll-target="#analysis-d-analyzing-a-2x2-table"><span class="header-section-number">8</span> Analysis D: Analyzing a 2x2 table</a></li>
  <li><a href="#analysis-e-analyzing-a-5x2-contingency-table" id="toc-analysis-e-analyzing-a-5x2-contingency-table" class="nav-link" data-scroll-target="#analysis-e-analyzing-a-5x2-contingency-table"><span class="header-section-number">9</span> Analysis E: Analyzing a 5x2 Contingency Table</a></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">NHANES Data Exploration (Heavy Metal Exposure &amp; High blood Pressure)</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Sofiya Vyshnya </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">2025-09-27</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="central-hypothesis" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Central Hypothesis</h1>
<p>My central hypothesis for this study is that middle-aged adults (age 40-65) adults with heavy metal exposure (e.g.&nbsp;lead exposure) have higher systolic blood pressure. To test this hypothesis, I am using data gathered from NHANES during the years of 2017-March 2020 (the pre-pandemic years). In this study (Study 1 analyses), I am performing data exploration to understand the distributions for each variable and investigate relationships between variables.</p>
</section>
<section id="import-helper-functions" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Import Helper Functions</h1>
</section>
<section id="setup-and-data-ingest" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Setup and Data Ingest</h1>
<p>The dataset consists of 2475 adults ages 40-65 participating in NHANES 2017-2020. The original NHANES data from 2017-2020 contained 9254 observations collected from individuals age 0-80. However, after selecting individuals aged 40-65, 2475 individuals were left.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(nhanesA)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressWarnings</span>(<span class="fu">library</span>(dplyr))</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Download three datasets</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>demo  <span class="ot">&lt;-</span> <span class="fu">nhanes</span>(<span class="st">"DEMO_J"</span>)   <span class="co"># demographics</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>pbcd  <span class="ot">&lt;-</span> <span class="fu">nhanes</span>(<span class="st">"PBCD_J"</span>)   <span class="co"># heavy metals (lead, cadmium, manganese) in blood</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>bpx   <span class="ot">&lt;-</span> <span class="fu">nhanes</span>(<span class="st">"BPX_J"</span>)    <span class="co"># blood pressure</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Merge them</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>nhanes_data <span class="ot">&lt;-</span> <span class="fu">Reduce</span>(<span class="cf">function</span>(x, y) <span class="fu">merge</span>(x, y, <span class="at">by =</span> <span class="st">"SEQN"</span>, <span class="at">all =</span> <span class="cn">TRUE</span>),</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>                      <span class="fu">list</span>(demo, pbcd, bpx))</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Pull out only variables of interest</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>nhanes_subset <span class="ot">&lt;-</span> nhanes_data <span class="sc">%&gt;%</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>    SEQN,       <span class="co"># participant ID</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>    RIDAGEYR,   <span class="co"># age</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>    RIAGENDR,   <span class="co"># gender</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>    RIDRETH1,   <span class="co"># race</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>    LBXBPB,     <span class="co"># blood lead</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>    LBXBCD,     <span class="co"># blood cadmium</span></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>    LBXBMN,     <span class="co"># blood manganese</span></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>    BPXSY1,     <span class="co"># systolic BP</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>    BPXDI1,     <span class="co"># diastolic BP</span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter for participants 18–65 years old </span></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>nhanes_filtered <span class="ot">&lt;-</span> nhanes_subset <span class="sc">%&gt;%</span> </span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(RIDAGEYR <span class="sc">&gt;=</span> <span class="dv">40</span>, RIDAGEYR <span class="sc">&lt;=</span> <span class="dv">65</span>) <span class="sc">%&gt;%</span></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Re-name "Other Race - Including Multi-Racial" category in RIDRETH1 to Exclude Prohibited Characters </span></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>( </span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>    <span class="at">RIDRETH1 =</span> <span class="fu">fct_recode</span>(RIDRETH1, <span class="st">"Other/Multiracial"</span> <span class="ot">=</span> <span class="st">"Other Race - Including Multi-Racial"</span>) </span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a><span class="co"># Save to RDS for later use</span></span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a><span class="fu">saveRDS</span>(nhanes_filtered, here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"data/nhanes_data.rds"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="data-cleaning" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Data Cleaning</h1>
<p><em>General:</em> Individuals with missing data for any of the variables listed in Table 1 were removed.</p>
<p><em>Numeric Variable Processing:</em> Outliers (defined as values &lt; Q1- 1.5<em>IQR or &gt; Q3+1.5</em>IQR) were removed. Numeric variables were subsequently log-transformed to make them approximately log-normal (see histograms below).</p>
<p>The resulting dataset has 1590 observations.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate plots showing data distribution for all numeric variables. Show the original distribution, the distribution after removing outliers, and the distribution after log transforming the data. </span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>p_lead      <span class="ot">&lt;-</span> <span class="fu">visualize_data</span>(nhanes_filtered, <span class="st">"LBXBPB"</span>, <span class="st">"Blood Lead"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>p_cadmium   <span class="ot">&lt;-</span> <span class="fu">visualize_data</span>(nhanes_filtered, <span class="st">"LBXBCD"</span>, <span class="st">"Blood Cadmium"</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>p_manganese <span class="ot">&lt;-</span> <span class="fu">visualize_data</span>(nhanes_filtered, <span class="st">"LBXBMN"</span>, <span class="st">"Blood Manganese"</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>final_plot <span class="ot">&lt;-</span> (p_lead <span class="sc">/</span> p_cadmium <span class="sc">/</span> p_manganese) <span class="co"># stacks plots for each variable on top of each other</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>final_plot</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="nhanes_data_exploration_files/figure-html/unnamed-chunk-3-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1"><img src="nhanes_data_exploration_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Lab data: remove outliers and log normalize the data</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>numeric_vars <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"LBXBPB"</span>, <span class="st">"LBXBCD"</span>, <span class="st">"LBXBMN"</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>nhanes_clean <span class="ot">&lt;-</span> nhanes_filtered <span class="sc">%&gt;%</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Remove outliers -&gt; temporary "_clean" columns</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">all_of</span>(numeric_vars), remove_outliers, <span class="at">.names =</span> <span class="st">"{.col}_clean"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Log-transform -&gt; new "_log" columns</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">ends_with</span>(<span class="st">"_clean"</span>), <span class="sc">~</span><span class="fu">log1p</span>(.), <span class="at">.names =</span> <span class="st">"{.col}_log"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Drop rows with NA values introduced by outlier removal</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>()</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Blood pressure data: remove outliers but don't log transform (data already roughly Gaussian)</span></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>numeric_vars <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"BPXSY1"</span>, <span class="st">"BPXDI1"</span>)</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>nhanes_clean <span class="ot">&lt;-</span> nhanes_clean <span class="sc">%&gt;%</span></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Remove outliers -&gt; "_clean" columns</span></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">all_of</span>(numeric_vars), remove_outliers, <span class="at">.names =</span> <span class="st">"{.col}_clean"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Drop rows with NA values introduced by outlier removal</span></span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>()</span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Save cleaned data </span></span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a><span class="fu">saveRDS</span>(nhanes_clean, here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"data/study1/nhanes_data_cleaned.rds"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="dataset-description-and-codebook" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Dataset Description and Codebook</h1>
<section id="dataset-description-summary-statistics" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="dataset-description-summary-statistics"><span class="header-section-number">5.1</span> Dataset Description &amp; Summary Statistics</h2>
<p>Table 1: Variables included in the data.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: left;">Description</th>
<th style="text-align: left;">Data Type</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>SEQN</strong></td>
<td style="text-align: left;">Subject ID: Individual Identifier</td>
<td style="text-align: left;">Quantitative (Integer)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>RIDAGEYR</strong></td>
<td style="text-align: left;">Age: Age in years at screening, range 40-65</td>
<td style="text-align: left;">Quantitative (Integer)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>RIAGENDR</strong></td>
<td style="text-align: left;">Sex: male or female</td>
<td style="text-align: left;">Binary</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>RIDRETH1</strong></td>
<td style="text-align: left;">Race</td>
<td style="text-align: left;">Multi-level Categorical</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>LBXBPB</strong></td>
<td style="text-align: left;">Blood lead (µg/dL)</td>
<td style="text-align: left;">Quantitative (Continuous)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>LBXBPB_clean_log</strong></td>
<td style="text-align: left;">Blood lead after outlier removal and log transformation</td>
<td style="text-align: left;">Quantitative (Continuous)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>LBXBCD</strong></td>
<td style="text-align: left;">Blood cadmium (µg/dL)</td>
<td style="text-align: left;">Quantitative (Continuous)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>LBXBCD_clean_log</strong></td>
<td style="text-align: left;">Blood cadmium (µg/dL) after outlier removal and log transformation</td>
<td style="text-align: left;">Quantitative (Continuous)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>LBXBMN</strong></td>
<td style="text-align: left;">Blood manganese (µg/dL)</td>
<td style="text-align: left;">Quantitative (Continuous)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>LBXBMN_clean_log</strong></td>
<td style="text-align: left;">Blood manganese (µg/dL) after outlier removal and log transformation</td>
<td style="text-align: left;">Quantitative (Continuous)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>BPXSY1</strong></td>
<td style="text-align: left;">Systolic BP, first reading</td>
<td style="text-align: left;">Quantitative (Integer)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>BPXSY1_clean</strong></td>
<td style="text-align: left;">Systolic BP, first reading, after outlier removal</td>
<td style="text-align: left;">Quantitative (Integer)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>BPXDI1</strong></td>
<td style="text-align: left;">Diastolic BP, first reading</td>
<td style="text-align: left;">Quantitative (Integer)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>BPXDI1_clean</strong></td>
<td style="text-align: left;">Diastolic BP, first reading, after outlier removal</td>
<td style="text-align: left;">Quantitative (Integer)</td>
</tr>
</tbody>
</table>
<p>Summary statistics for the continuous and categorical variables:</p>
<p>Table 2: Summary of numeric data.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: left;">mean</th>
<th style="text-align: left;">stdev</th>
<th style="text-align: left;">median</th>
<th style="text-align: left;">min</th>
<th style="text-align: left;">max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>RIDAGEYR</strong></td>
<td style="text-align: left;">53.67</td>
<td style="text-align: left;">7.54</td>
<td style="text-align: left;">55.00</td>
<td style="text-align: left;">40.00</td>
<td style="text-align: left;">65.00</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>LBXBPB</strong></td>
<td style="text-align: left;">1.36</td>
<td style="text-align: left;">1.69</td>
<td style="text-align: left;">1.02</td>
<td style="text-align: left;">0.12</td>
<td style="text-align: left;">42.48</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>LBXBCD</strong></td>
<td style="text-align: left;">0.53</td>
<td style="text-align: left;">0.60</td>
<td style="text-align: left;">0.34</td>
<td style="text-align: left;">0.07</td>
<td style="text-align: left;">7.50</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>LBXBMN</strong></td>
<td style="text-align: left;">10.07</td>
<td style="text-align: left;">3.78</td>
<td style="text-align: left;">9.39</td>
<td style="text-align: left;">1.57</td>
<td style="text-align: left;">35.56</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>BPXSY1</strong></td>
<td style="text-align: left;">127.95</td>
<td style="text-align: left;">18.52</td>
<td style="text-align: left;">126.00</td>
<td style="text-align: left;">78.00</td>
<td style="text-align: left;">224.00</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>BPXDI1</strong></td>
<td style="text-align: left;">76.06</td>
<td style="text-align: left;">12.04</td>
<td style="text-align: left;">76.00</td>
<td style="text-align: left;">0.00</td>
<td style="text-align: left;">124.00</td>
</tr>
</tbody>
</table>
<p>Table 3: Summary of categorical data.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: left;">Count (Percent)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>RIAGENDR: Sex</strong></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Male</td>
<td style="text-align: left;">975 (48.39%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Female</td>
<td style="text-align: left;">1040 (51.61%)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>RIDRETH1: Race</strong></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mexican American</td>
<td style="text-align: left;">303 (15.03%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Other Hispanic</td>
<td style="text-align: left;">208 (10.32%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Non-Hispanic White</td>
<td style="text-align: left;">581 (28.83%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Non-Hispanic Black</td>
<td style="text-align: left;">483 (23.97%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Other Race - Including Multi-Racial</td>
<td style="text-align: left;">440 (21.84%)</td>
</tr>
</tbody>
</table>
</section>
<section id="codebook-html-rendering" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="codebook-html-rendering"><span class="header-section-number">5.2</span> Codebook (HTML Rendering)</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(labelled)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dataReporter)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Assign variable labels</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>var_labels <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">SEQN =</span> <span class="st">"Subject ID: Individual Identifier"</span>,</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">RIDAGEYR =</span> <span class="st">"Age in years at screening (40-65)"</span>,</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">RIAGENDR =</span> <span class="st">"Sex: male or female"</span>,</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">RIDRETH1 =</span> <span class="st">"Race / Ethnicity"</span>,</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">LBXBPB =</span> <span class="st">"Blood lead (µg/dL)"</span>,</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">LBXBPB_clean_log =</span> <span class="st">"Blood lead after outlier removal and log transformation"</span>,</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">LBXBCD =</span> <span class="st">"Blood cadmium (µg/dL)"</span>,</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">LBXBCD_clean_log =</span> <span class="st">"Blood cadmium after outlier removal and log transformation"</span>,</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">LBXBMN =</span> <span class="st">"Blood manganese (µg/dL)"</span>,</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">LBXBMN_clean_log =</span> <span class="st">"Blood manganese after outlier removal and log transformation"</span>,</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">BPXSY1 =</span> <span class="st">"Systolic BP, first reading"</span>,</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">BPXSY1_clean =</span> <span class="st">"Systolic BP, first reading after outlier removal"</span>,</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">BPXDI1 =</span> <span class="st">"Diastolic BP, first reading"</span>,</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">BPXDI1_clean =</span> <span class="st">"Diastolic BP, first reading after outlier removal"</span></span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert your named character vector to a named list</span></span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>var_labels_list <span class="ot">&lt;-</span> <span class="fu">as.list</span>(var_labels)</span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply labels to the dataframe</span></span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>nhanes_clean <span class="ot">&lt;-</span> <span class="fu">set_variable_labels</span>(nhanes_clean, <span class="at">.labels =</span> var_labels_list)</span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a><span class="fu">makeCodebook</span>(nhanes_clean, <span class="at">file =</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"data/study1/codebook.html"</span>), <span class="at">output =</span> <span class="st">"html"</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="codebook-table-rendering" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="codebook-table-rendering"><span class="header-section-number">5.3</span> Codebook (Table Rendering)</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 15 × 9
   variable        type  missing     min     q25  median    mean     q75     max
   &lt;chr&gt;           &lt;chr&gt;   &lt;int&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
 1 SEQN            nume…       0 9.37e+4 9.60e+4 9.83e+4 9.83e+4 1.01e+5 1.03e+5
 2 RIDAGEYR        nume…       0 4   e+1 4.7 e+1 5.5 e+1 5.37e+1 6   e+1 6.5 e+1
 3 LBXBPB          nume…       0 1.2 e-1 6.1 e-1 9.3 e-1 1.03e+0 1.33e+0 2.77e+0
 4 LBXBCD          nume…       0 7   e-2 1.8 e-1 3   e-1 3.68e-1 4.8 e-1 1.21e+0
 5 LBXBMN          nume…       0 3.07e+0 7.49e+0 9.28e+0 9.67e+0 1.15e+1 1.83e+1
 6 BPXSY1          nume…       0 8.8 e+1 1.16e+2 1.26e+2 1.26e+2 1.36e+2 1.7 e+2
 7 BPXDI1          nume…       0 5.2 e+1 7   e+1 7.6 e+1 7.60e+1 8.2 e+1 1   e+2
 8 LBXBPB_clean    nume…       0 1.2 e-1 6.1 e-1 9.3 e-1 1.03e+0 1.33e+0 2.77e+0
 9 LBXBCD_clean    nume…       0 7   e-2 1.8 e-1 3   e-1 3.68e-1 4.8 e-1 1.21e+0
10 LBXBMN_clean    nume…       0 3.07e+0 7.49e+0 9.28e+0 9.67e+0 1.15e+1 1.83e+1
11 LBXBPB_clean_l… nume…       0 1.13e-1 4.76e-1 6.58e-1 6.77e-1 8.46e-1 1.33e+0
12 LBXBCD_clean_l… nume…       0 6.77e-2 1.66e-1 2.62e-1 2.98e-1 3.92e-1 7.93e-1
13 LBXBMN_clean_l… nume…       0 1.40e+0 2.14e+0 2.33e+0 2.33e+0 2.52e+0 2.96e+0
14 BPXSY1_clean    nume…       0 8.8 e+1 1.16e+2 1.26e+2 1.26e+2 1.36e+2 1.7 e+2
15 BPXDI1_clean    nume…       0 5.2 e+1 7   e+1 7.6 e+1 7.60e+1 8.2 e+1 1   e+2</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  variable type   missing n_unique levels                                       
  &lt;chr&gt;    &lt;chr&gt;    &lt;int&gt;    &lt;int&gt; &lt;chr&gt;                                        
1 RIAGENDR factor       0        2 Male, Female                                 
2 RIDRETH1 factor       0        5 Other/Multiracial, Non-Hispanic Black, Mexic…</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 4
  variable level              count missing
  &lt;chr&gt;    &lt;fct&gt;              &lt;int&gt;   &lt;int&gt;
1 RIAGENDR Male                 769       0
2 RIAGENDR Female               821       0
3 RIDRETH1 Mexican American     249       0
4 RIDRETH1 Other Hispanic       179       0
5 RIDRETH1 Non-Hispanic White   459       0
6 RIDRETH1 Non-Hispanic Black   376       0
7 RIDRETH1 Other/Multiracial    327       0</code></pre>
</div>
</div>
</section>
<section id="analytic-tibble" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="analytic-tibble"><span class="header-section-number">5.4</span> Analytic Tibble</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   SEQN RIDAGEYR RIAGENDR           RIDRETH1 LBXBPB LBXBCD LBXBMN BPXSY1 BPXDI1
1 93711       56     Male  Other/Multiracial   2.15   0.38   6.55    108     68
2 93716       61     Male  Other/Multiracial   1.99   0.23   8.80    120     72
3 93718       45     Male Non-Hispanic Black   0.62   0.10  12.00    128     88
4 93721       60   Female   Mexican American   0.75   0.18   9.92    132     68
5 93722       60   Female Non-Hispanic White   0.98   0.38  15.05    116     68
6 93723       64     Male Non-Hispanic White   0.99   0.19   7.68    124     72
  LBXBPB_clean LBXBCD_clean LBXBMN_clean LBXBPB_clean_log LBXBCD_clean_log
1         2.15         0.38         6.55        1.1474025       0.32208350
2         1.99         0.23         8.80        1.0952734       0.20701417
3         0.62         0.10        12.00        0.4824261       0.09531018
4         0.75         0.18         9.92        0.5596158       0.16551444
5         0.98         0.38        15.05        0.6830968       0.32208350
6         0.99         0.19         7.68        0.6881346       0.17395331
  LBXBMN_clean_log BPXSY1_clean BPXDI1_clean
1         2.021548          108           68
2         2.282382          120           72
3         2.564949          128           88
4         2.390596          132           68
5         2.775709          116           68
6         2.161022          124           72</code></pre>
</div>
</div>
</section>
</section>
<section id="summary-statistics" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Summary Statistics</h1>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                 vars    n     mean      sd   median  trimmed     mad      min
SEQN                1 1590 98347.85 2731.06 98328.50 98347.99 3509.31 93711.00
RIDAGEYR            2 1590    53.67    7.57    55.00    53.95    8.90    40.00
RIAGENDR*           3 1590     1.52    0.50     2.00     1.52    0.00     1.00
RIDRETH1*           4 1590     3.22    1.32     3.00     3.28    1.48     1.00
LBXBPB              5 1590     1.03    0.54     0.93     0.98    0.52     0.12
LBXBCD              6 1590     0.37    0.25     0.30     0.33    0.19     0.07
LBXBMN              7 1590     9.67    2.98     9.27     9.49    2.94     3.07
BPXSY1              8 1590   126.18   15.69   126.00   125.60   14.83    88.00
BPXDI1              9 1590    76.00    9.69    76.00    75.94    8.90    52.00
LBXBPB_clean       10 1590     1.03    0.54     0.93     0.98    0.52     0.12
LBXBCD_clean       11 1590     0.37    0.25     0.30     0.33    0.19     0.07
LBXBMN_clean       12 1590     9.67    2.98     9.27     9.49    2.94     3.07
LBXBPB_clean_log   13 1590     0.68    0.25     0.66     0.67    0.27     0.11
LBXBCD_clean_log   14 1590     0.30    0.17     0.26     0.28    0.15     0.07
LBXBMN_clean_log   15 1590     2.33    0.28     2.33     2.33    0.29     1.40
BPXSY1_clean       16 1590   126.18   15.69   126.00   125.60   14.83    88.00
BPXDI1_clean       17 1590    76.00    9.69    76.00    75.94    8.90    52.00
                       max   range  skew kurtosis    se
SEQN             102954.00 9243.00  0.01    -1.21 68.49
RIDAGEYR             65.00   25.00 -0.25    -1.19  0.19
RIAGENDR*             2.00    1.00 -0.07    -2.00  0.01
RIDRETH1*             5.00    4.00 -0.28    -0.97  0.03
LBXBPB                2.77    2.65  0.90     0.43  0.01
LBXBCD                1.21    1.14  1.21     0.91  0.01
LBXBMN               18.34   15.27  0.50    -0.15  0.07
BPXSY1              170.00   82.00  0.34    -0.19  0.39
BPXDI1              100.00   48.00  0.04    -0.27  0.24
LBXBPB_clean          2.77    2.65  0.90     0.43  0.01
LBXBCD_clean          1.21    1.14  1.21     0.91  0.01
LBXBMN_clean         18.34   15.27  0.50    -0.15  0.07
LBXBPB_clean_log      1.33    1.21  0.35    -0.47  0.01
LBXBCD_clean_log      0.79    0.73  0.87     0.04  0.00
LBXBMN_clean_log      2.96    1.56 -0.18    -0.22  0.01
BPXSY1_clean        170.00   82.00  0.34    -0.19  0.39
BPXDI1_clean        100.00   48.00  0.04    -0.27  0.24</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  variable              level   n Proportion
1 RIAGENDR               Male 769  0.4836478
2 RIAGENDR             Female 821  0.5163522
3 RIDRETH1   Mexican American 249  0.1566038
4 RIDRETH1     Other Hispanic 179  0.1125786
5 RIDRETH1 Non-Hispanic White 459  0.2886792
6 RIDRETH1 Non-Hispanic Black 376  0.2364780
7 RIDRETH1  Other/Multiracial 327  0.2056604</code></pre>
</div>
</div>
</section>
<section id="study-1-analyses" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Study 1 Analyses</h1>
<section id="analysis-b-comparing-2-means-with-independent-samples-blood-lead-levels-by-sex" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="analysis-b-comparing-2-means-with-independent-samples-blood-lead-levels-by-sex"><span class="header-section-number">7.1</span> Analysis B: Comparing 2 Means with Independent Samples (Blood Lead Levels by Sex)</h2>
<p><strong>Question:</strong> Is the blood lead level different in males and females?</p>
<p><strong>Dataset Description:</strong> The dataset was stratified by sex. Mean blood lead levels (LBXBPB_clean_log), were compared between the two sexes (male, female). There were 769 males and 821 females in the dataset.</p>
<p><strong>Main analysis:</strong> A two-tailed t-test was used to compare the difference in mean blood lead levels (log-transformed) between males and females. A significance level of 0.1 was used. The effect size (Cohen’s d) was also computed (small: 0.2, medium: 0.5, large: 0.8). This set-up is essentially equivalent to univariate OLS, where the beta coefficient (<span class="math inline">\(\beta_1\)</span>) corresponds to the difference in means of the two groups and the intercept (<span class="math inline">\(\beta_0\)</span>) corresponds to the mean lead concentration of the reference group. OLS assumes that the data (or rather, the errors) follow a normal distribution, the errors are independent, and the errors have a constant variance. <span class="math display">\[log(lead\_conc) = \beta_0 + \beta_1(male\_sex)\]</span> <span class="math display">\[lead\_conc = e^{\beta_0 + \beta_1(male\_sex)}\]</span> <span class="math display">\[\text{Fold change }lead\_conc = e^{\beta_1}\]</span></p>
<p><strong>Conclusions:</strong> The median blood lead level was 0.71 ± 0.25 (mean ± SD) for males and 0.65 ± 0.25 for females, which translates to a 6% (difference in means: 0.71-0.65 = 0.06 <span class="math inline">\(\rightarrow\)</span> fold change: <span class="math inline">\(e^{0.06} = 1.06\)</span>, <span class="math inline">\(\rightarrow\)</span> 6% increase) difference in blood lead concentrations between males and females. The difference was statistically significant at the 0.1 level, but the effect size was low (0.26). I conclude that males and females have no appreciable difference in blood lead levels.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 9
  n_Male n_Female mean_Male mean_Female sd_Male sd_Female t_statistic   p_value
   &lt;int&gt;    &lt;int&gt;     &lt;dbl&gt;       &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt;     &lt;dbl&gt;
1    769      821     0.711       0.646   0.248     0.251        5.15 0.0000003
# ℹ 1 more variable: cohen_d &lt;dbl&gt;</code></pre>
</div>
</div>
</section>
<section id="analysis-c-comparing-blood-lead-levels-across-races" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="analysis-c-comparing-blood-lead-levels-across-races"><span class="header-section-number">7.2</span> Analysis C: Comparing Blood Lead Levels Across Races</h2>
<p><strong>Question:</strong> Are blood lead levels different between races?</p>
<p><strong>Dataset Description:</strong> The dataset was stratified by race (Mexican American, other Hispanic, non-Hispanic white, non-Hispanic black, other/multiracial). Mean blood levels of lead (LBXBPB_clean_log), were compared across the 5 racial/ethnic groups. There were 459 individuals identifying as non-Hispanic white, 249 individuals identifying as Mexican American, 179 as other Hispanic, 376 as non-Hispanic black, and 327 as other/multiracial.</p>
<p><strong>Main analysis:</strong> Race/ethnicity was dummy-coded. A multivariate OLS model was used to compare mean blood lead levels, setting non-Hispanic white as the reference group. A significance level of 0.1 was used. This set-up is similar to an ANOVA followed by post-hoc testing. OLS assumes that the errors are iid, follow a normal distribution with a mean of 0, and have constant variance.</p>
<p><strong>Conclusions:</strong> The mean blood lead level was 0.64 ± 0.25 (mean ± SD) for non-Hispanic whites, 0.66 ± 0.24 for Mexican Americans, 0.59 ± 0.24 for other Hispanics, 0.71 ± 0.26 for blacks, and 0.74 ± 0.24 for multiracial individuals. This translates into a 1.7% increase in blood lead levels in Mexican Americans compared to non-Hispanic whites, a 5.2% decrease in other Hispanics, a 6.23% increase in black individuals, and a 10.0% increase in blood lead levels multiracial individuals. All the comparisons were statistically significant except for Mexican Americans, whose blood lead levels were closer to the reference group. In conclusion,</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 4
  group              mean_LBXBPB_log sd_LBXBPB_log     n
  &lt;fct&gt;                        &lt;dbl&gt;         &lt;dbl&gt; &lt;int&gt;
1 Mexican American             0.664         0.237   249
2 Other Hispanic               0.594         0.237   179
3 Non-Hispanic White           0.647         0.252   459
4 Non-Hispanic Black           0.708         0.262   376
5 Other/Multiracial            0.741         0.239   327</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = LBXBPB_clean_log ~ RIDRETH1, data = nhanes_clean)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.55052 -0.18873 -0.02102  0.16841  0.67480 

Coefficients:
                           Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                 0.64696    0.01156  55.973  &lt; 2e-16 ***
RIDRETH1Mexican American    0.01694    0.01949   0.869  0.38494    
RIDRETH1Other Hispanic     -0.05336    0.02182  -2.445  0.01458 *  
RIDRETH1Non-Hispanic Black  0.06056    0.01722   3.516  0.00045 ***
RIDRETH1Other/Multiracial   0.09438    0.01792   5.267 1.58e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2476 on 1585 degrees of freedom
Multiple R-squared:  0.03385,   Adjusted R-squared:  0.03142 
F-statistic: 13.88 on 4 and 1585 DF,  p-value: 3.898e-11</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  group              fold_change percent_change
  &lt;chr&gt;                    &lt;dbl&gt;          &lt;dbl&gt;
1 Mexican American         1.02            1.71
2 Other Hispanic           0.948          -5.20
3 Non-Hispanic Black       1.06            6.24
4 Other/Multiracial        1.10            9.90</code></pre>
</div>
</div>
</section>
</section>
<section id="analysis-d-analyzing-a-2x2-table" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Analysis D: Analyzing a 2x2 table</h1>
<p><strong>Question:</strong> Is the proportion of adults with high systolic blood pressure (&gt;140 mmHg) different between males and females?</p>
<p><strong>Dataset Description:</strong> There were 769 males and 821 females in the dataset. There were 280 individuals with high systolic BP and 1310 individuals with normal-low systolic BP. The exposure or grouping variable is sex (male/female). The outcome variable is high blood pressure (Yes/No). (It doesn’t quite make sense to think of sex as an “exposure”, but if we had something like “smoking” or “adverse childhood experiences” here, we could easily consider them exposures.) Of the males, 139 have high blood pressure, and 630 don’t. Of the females, 141 have high blood pressure, and 680 don’t. Ideally, this analysis would also be stratified by age (as males and females might have a different age distribution, and age is correlated with high BP), but that’s outside the scope of this analysis.</p>
<p><strong>Main analysis:</strong> A two-way contingency table was used to determine the frequency of adverse outcomes (high systolic blood pressure) across the two exposure groups, and a chi squared test was used to assess statistical significance. A significance level of 0.1 was used. The null hypothesis is that high BP is equally likely in males and females, and the two variables (sex and high BP) are independent. In other words, the joint probability is the product of the marginal probabilities: <span class="math inline">\(P(\text{male and high BP}) = P(male) \times P(\text{high BP})\)</span>. The expected counts for the 2x2 contingency table are derived from the joint probabilities under the assumption of independence (expected counts = joint probability * n). The null hypothesis will be rejected if the actual counts different significantly from the expected counts, meaning that the marginal probabilities are not independent. The chi squared test assumes that variables are categorical. Expected counts should be &gt;5 for each cell (if not, a Fisher’s exact test should be used).</p>
<p><strong>Conclusions:</strong> X-squared = 0.16451, df = 1, p-value = 0.685. We fail to reject the null hypothesis, meaning that we have no evidence to suggest that males and females have different rates of high blood pressure in our sample.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test with Yates' continuity correction

data:  tab
X-squared = 0.16451, df = 1, p-value = 0.685</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>$data
        
           No Yes Total
  Male    630 139   769
  Female  680 141   821
  Total  1310 280  1590

$measure
        odds ratio with 95% C.I.
          estimate     lower   upper
  Male   1.0000000        NA      NA
  Female 0.9398292 0.7257268 1.21723

$p.value
        two-sided
         midp.exact fisher.exact chi.square
  Male           NA           NA         NA
  Female  0.6378242    0.6452509  0.6372994

$correction
[1] FALSE

attr(,"method")
[1] "median-unbiased estimate &amp; mid-p exact CI"</code></pre>
</div>
</div>
</section>
<section id="analysis-e-analyzing-a-5x2-contingency-table" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> Analysis E: Analyzing a 5x2 Contingency Table</h1>
<p><strong>Question:</strong> Is the proportion of adults with high systolic blood pressure (&gt;140 mmHg) different between different racial and ethnic groups?</p>
<p><strong>Dataset Description:</strong> There were 459 individuals identifying as non-Hispanic white, 249 individuals identifying as Mexican American, 179 as other Hispanic, 376 as non-Hispanic black, and 327 as other/multiracial. There were 280 individuals with high systolic BP and 1310 individuals with normal-low systolic BP.</p>
<p><strong>Main analysis:</strong> A chi square test was used to assess whether the probability of having high systolic BP is different across different racial/ethnic groups. The null hypothesis is that the probability of adults having high BP is the same across all racial/ethnic groups (the expected counts don’t all have to be the same because we have a different number of people from each racial/ethnic group, but they all have the same probability of having high BP). A significance level of 0.1 was used.</p>
<p><strong>Conclusions:</strong> The probability of having high systolic blood pressure does differ slightly by racial and ethnic group (X-squared = 23.096, df = 4, p-value = 0.0001211, Cramer’s V = 0.1205, indicating a small effect size). The actual difference is not very large, but it is statistically significant due to the large sample size. Non-Hispanic whites have disproportionately lower proportion of individuals with high systolic BP (Pearson residual &lt; -2), while non-Hispanic blacks have a disproportionately higher proportion of people with high BP (Pearson residual &gt; 2).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>tab <span class="ot">&lt;-</span> <span class="fu">table</span>(nhanes_clean<span class="sc">$</span>RIDRETH1, nhanes_clean<span class="sc">$</span>HighBP)  <span class="co"># Race x BP category</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>chisq_res <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(tab)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>chisq_res</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  tab
X-squared = 23.096, df = 4, p-value = 0.0001211</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cramer's V</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rcompanion)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cramerV</span>(tab)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Cramer V 
  0.1205 </code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                    
                             No        Yes
  Non-Hispanic White  1.0711487 -2.3168953
  Mexican American    0.1290962 -0.2792351
  Other Hispanic     -0.1217046  0.2632472
  Non-Hispanic Black -1.6355084  3.5376056
  Other/Multiracial   0.4621035 -0.9995300</code></pre>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>